# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  username: collective
  password: coll1231234
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: collective_dev

test:
  <<: *default
  database: collective_test

